### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by rodluger** [jfcrenshaw/pzflow-paper#1]
Hey @jfcrenshaw I tried running your workflow from scratch but there's no rule to generate [this file](https://github.com/jfcrenshaw/pzflow-paper/blob/bb4ed07efeb74750fa78b97a3dff91fc4e53429e/src/scripts/train_conditional_galaxy_flow.py#L12). Is there a way to make it publicly available, or do you want third-party users to only go through the cache?

**Comment by jfcrenshaw** [comment]
Ah yes, I was planning on publishing that file on Zenodo with all of the other files when I publish the paper (hence [this issue](https://github.com/showyourwork/showyourwork/issues/100)), but I guess I should go ahead and make it available.

**Comment by jfcrenshaw** [comment]
@rodluger you can download the data file [here](https://github.com/jfcrenshaw/pzflow-paper-2021/releases/download/data/dc2.pkl)

**Comment by jfcrenshaw** [comment]
I just updated the scripts so that testing should be pretty fast now.
